name: test

on:
  push:

jobs:
  docker-build:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker Compose Version
        run: docker-compose --version

      - name: Build Docker
        run: docker-compose up -d --build

      - name: PHP Version
        run: docker-compose exec -T app php --version

      - name: Composer Version
        run: docker-compose exec -T app composer --version

      - name: Copy .env
        run: docker-compose exec -T app php -r "copy('.env.example', '.env');"

      - name: Install Dependencies
        run: docker-compose exec -T app composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: docker-compose exec -T app php artisan key:generate

      - name: Directory Permissions
        run: docker-compose exec -T app chmod -R 777 storage bootstrap/cache

      - name: Laravel Version
        run: docker-compose exec -T app php artisan --version

      - name: Laravel Migrate Testing
        run: docker-compose exec -T app php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T app php artisan migrate:refresh --seed

      - name: Laravel Seeding Testing
        run: docker-compose exec -T app php artisan db:seed

      - name: Check Coding Standards
        run: ocker-compose exec -T app composer cs

      - name: Laravel PHPUnit Testing
        run: docker-compose exec -T app php artisan test